apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name | lower | replace "_" "-"}}"
  labels:
    proj: "{{ .Release.Name }}"
    slave_microservice: "{{ .Chart.Name | lower | replace "_" "-" }}"
spec:
  selector:
    app: {{.Chart.Name | lower | replace "_" "-"}}
  type: {{ default "ClusterIP" .Values.service.type}}
  ports: {{ if .Values.ports }}
{{ toYaml .Values.ports | indent 4}}
    {{ else }}
    - port: {{ .Values.port }}
    {{- end -}}
    